# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puppy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('size', models.CharField(max_length=15)),
            ],
        ),
    ]
